apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  topswatch.yaml: |
    server:
      address: "{{ .Values.config.server.address }}"
      port: {{ .Values.config.server.port }}
    collector:
      interval: {{ .Values.config.collector.interval }}
      history: {{ .Values.config.collector.history }}
      process_rescan: {{ dig "processRescan" "5s" .Values.config.collector }}
    collectors:
      cpu:
        enabled: {{ .Values.config.collectors.cpu.enabled }}
      gpu:
        enabled: {{ .Values.config.collectors.gpu.enabled }}
      npu:
        enabled: {{ .Values.config.collectors.npu.enabled }}
      power:
        enabled: {{ dig "power" "enabled" true .Values.config.collectors }}
